### PR TITLE
Add Feature : created profile with connect wallet button , Menu ~ Hacktoberfest 2022

### PR DESCRIPTION
**Pull request by Rahul-Prasad-07**
### What changes does this PR do? #5 
- created profile with connect wallet button
- Menu

### Screenshots (If any)
image

#5

### CODE REVIEW

**Review by suchit1010 — APPROVED** [review]
Looks good Rahul !
you can add some real images so it can be attractive !

**Review by PatelYash07 — APPROVED** [review]
Good work 👍

**Comment by Rahul-Prasad-07** [comment]
> Looks good Rahul ! you can add some real images so it can be attractive !

Okey i will add

**Comment by Rahul-Prasad-07** [comment]
> Good work 👍

Thanks

**Pull request merged**
